server:
  port: 7902

#spring:
#  profiles:
#    active: dev








datasource1:
  url: jdbc:mysql://localhost:3306/stock_base?useSSL=false&useUnicode=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

datasource2:
  url: jdbc:mysql://localhost:3306/stock_base?useSSL=false&useUnicode=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver

